# This file was generated by GoReleaser. DO NOT EDIT.
cask "nightshift" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "8210140d346cc6ee6b016b99f79661598005be257d638e5fa3b738e649daee43"
      url "https://github.com/ahmadAlMezaal/nightshift/releases/download/v#{version}/nightshift_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4c4fd5bd34297541ef274ef299c4fab138a6b6098831a92dd6f9c2a42f02d02c"
      url "https://github.com/ahmadAlMezaal/nightshift/releases/download/v#{version}/nightshift_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cf7e5ca80a6d670feeb084b39cfa5a9fe209c646fdafe9c5b2f0fa59244ba17c"
      url "https://github.com/ahmadAlMezaal/nightshift/releases/download/v#{version}/nightshift_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "da5568c65ca202777bbda9e641adcc80954666282be086bf309a27629eff1a86"
      url "https://github.com/ahmadAlMezaal/nightshift/releases/download/v#{version}/nightshift_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nightshift"
  desc "Autonomous Linear-to-PR agent — polls Linear for tickets, implements them with Claude Code or OpenAI Codex, and creates pull requests."
  homepage "https://getnightshift.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nightshift"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nightshift"]
    end
  end

  # No zap stanza required

end
