# This file was generated by GoReleaser. DO NOT EDIT.
cask "noctra" do
  version "0.17.0"

  on_macos do
    on_intel do
      sha256 "a58bf1f1ce61bfb29d2dcf39f95201300d72e8e7924a20c2d0f1d3a767cf39b5"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "477450c8c38ee39e4f8ceb46935f36fa0a2ef685d233a985e2d2abc14b568fa6"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b3262f33d11b7a11a9635ef2f24ea25fa71a0a4074033d59e4dda34d05922943"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ea512f0a1c1898213b00a2b3afe42989ac3fb3aebf1151291fd0761e194bc7a0"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_linux_arm64.tar.gz"
    end
  end

  name "noctra"
  desc "Autonomous Linear-to-PR agent — polls Linear for tickets, implements them with Claude Code or OpenAI Codex, and creates pull requests."
  homepage "https://getnoctra.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noctra"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noctra"]
    end
  end

  # No zap stanza required

end
