# This file was generated by GoReleaser. DO NOT EDIT.
cask "noctra" do
  version "0.30.0"

  on_macos do
    on_intel do
      sha256 "4b92d25df5cc0837af4dfd408eb3889dc7eb296ac8720a10e92dd10eee962794"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e9d58785661475b790cab31d0440feea516b7d1052a274df85afb75add667a7c"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9a7f222dbc2d567c0c6dbf21888262a6a1d075cef196ccc4f39f916529f73fc5"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4ffeb43f6ce6addebd0fdbf67b3f0f06a4ce28e1a96ed8c50f94bbe007a5fc06"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_linux_arm64.tar.gz"
    end
  end

  name "noctra"
  desc "Autonomous Linear-to-PR agent — polls Linear for tickets, implements them with Claude Code or OpenAI Codex, and creates pull requests."
  homepage "https://getnoctra.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noctra"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noctra"]
    end
  end

  # No zap stanza required

end
