# This file was generated by GoReleaser. DO NOT EDIT.
cask "noctra" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "7ad96f403bc2e96c8b7303dd326f4a0b09d2fa3dc108c22d5072e3d26eaf311c"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1fd7ed065ddd5954e734e5e2984e696463cb361d1b4504b0d22c33d0bb1859c9"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "41034cabf9d9bad48d8688fee3d3c991814d434eb8db2ba731876b3071285e6a"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ca525209f762fc10b2c224b36acd40fcf6130bf6ee71f282c6f0d480d0b96416"
      url "https://github.com/ahmadAlMezaal/noctra/releases/download/v#{version}/noctra_#{version}_linux_arm64.tar.gz"
    end
  end

  name "noctra"
  desc "Autonomous Linear-to-PR agent — polls Linear for tickets, implements them with Claude Code or OpenAI Codex, and creates pull requests."
  homepage "https://getnoctra.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "noctra"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/noctra"]
    end
  end

  # No zap stanza required

end
